name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
   Test:
    strategy:
      fail-fast: false

      matrix:
        platform:
        - { target: x86_64-pc-windows-gnu, os: windows-latest }
        - { target: x86_64-pc-windows-msvc, os: windows-latest }
        - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest }

    runs-on: ${{ matrix.platform.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
